version: '2.0'
services:
    ingestor-grpc:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        GRPC_SERVER: "persistence-grpc:50502"
      depends_on:
        - persistence-grpc
      entrypoint: bash -c "services-bi grpc"

    persistence-grpc:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        BIND: "persistence-grpc:50502"
        STORAGE_HOST: "postgres"
        STORAGE_PORT: 5432
        STORAGE_DATABASE: "postgres"
        STORAGE_USER: "postgres"
        STORAGE_PASSWORD: "postgres"
      depends_on:
        - postgres
      expose:
        - 50502
      entrypoint: bash -c "persistor-bi migrate && persistor-bi grpc"

    postgres:
      image: postgres
      expose:
        - 5432
      environment:
        POSTGRES_DB: "postgres"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
