// Automatically generated by MockGen. DO NOT EDIT!
// Source: google.golang.org/grpc/examples/proto/proto (interfaces: Persistor)

package main

import (
	"github.com/golang/mock/gomock"
	"github.com/nettyrnp/go-grpc/proto"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
)

// Mock of Persistor interface
type MockPersistor struct {
	ctrl     *gomock.Controller
	recorder *_MockPersistorRecorder
}

// Recorder for MockPersistor (not exported)
type _MockPersistorRecorder struct {
	mock *MockPersistor
}

func NewMockPersistor(ctrl *gomock.Controller) *MockPersistor {
	mock := &MockPersistor{ctrl: ctrl}
	mock.recorder = &_MockPersistorRecorder{mock}
	return mock
}

func (_m *MockPersistor) EXPECT() *_MockPersistorRecorder {
	return _m.recorder
}

func (_m *MockPersistor) SavePersons(_param0 context.Context, _param1 *proto.PersonsReq, _param2 ...grpc.CallOption) (*proto.PersonsReply, error) {
	_s := []interface{}{_param0, _param1}
	for _, _x := range _param2 {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "SavePersons", _s...)
	ret0, _ := ret[0].(*proto.PersonsReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPersistorRecorder) SavePersons(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0, arg1}, arg2...)
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SavePersons", _s...)
}
