// Code generated by protoc-gen-go. DO NOT EDIT.
// source: persistor.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PersonsReq struct {
	Persons              []*Person `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PersonsReq) Reset()         { *m = PersonsReq{} }
func (m *PersonsReq) String() string { return proto.CompactTextString(m) }
func (*PersonsReq) ProtoMessage()    {}
func (*PersonsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_persistor_e7bf3953f5146b35, []int{0}
}
func (m *PersonsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonsReq.Unmarshal(m, b)
}
func (m *PersonsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonsReq.Marshal(b, m, deterministic)
}
func (dst *PersonsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonsReq.Merge(dst, src)
}
func (m *PersonsReq) XXX_Size() int {
	return xxx_messageInfo_PersonsReq.Size(m)
}
func (m *PersonsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonsReq.DiscardUnknown(m)
}

var xxx_messageInfo_PersonsReq proto.InternalMessageInfo

func (m *PersonsReq) GetPersons() []*Person {
	if m != nil {
		return m.Persons
	}
	return nil
}

type PersonsReply struct {
	CreatedCount         int32    `protobuf:"varint,1,opt,name=createdCount,proto3" json:"createdCount,omitempty"`
	UpdatedCount         int32    `protobuf:"varint,2,opt,name=updatedCount,proto3" json:"updatedCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonsReply) Reset()         { *m = PersonsReply{} }
func (m *PersonsReply) String() string { return proto.CompactTextString(m) }
func (*PersonsReply) ProtoMessage()    {}
func (*PersonsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_persistor_e7bf3953f5146b35, []int{1}
}
func (m *PersonsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonsReply.Unmarshal(m, b)
}
func (m *PersonsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonsReply.Marshal(b, m, deterministic)
}
func (dst *PersonsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonsReply.Merge(dst, src)
}
func (m *PersonsReply) XXX_Size() int {
	return xxx_messageInfo_PersonsReply.Size(m)
}
func (m *PersonsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonsReply.DiscardUnknown(m)
}

var xxx_messageInfo_PersonsReply proto.InternalMessageInfo

func (m *PersonsReply) GetCreatedCount() int32 {
	if m != nil {
		return m.CreatedCount
	}
	return 0
}

func (m *PersonsReply) GetUpdatedCount() int32 {
	if m != nil {
		return m.UpdatedCount
	}
	return 0
}

type Person struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	MobileNumber         string   `protobuf:"bytes,4,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_persistor_e7bf3953f5146b35, []int{2}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (dst *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(dst, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetMobileNumber() string {
	if m != nil {
		return m.MobileNumber
	}
	return ""
}

func init() {
	proto.RegisterType((*PersonsReq)(nil), "proto.PersonsReq")
	proto.RegisterType((*PersonsReply)(nil), "proto.PersonsReply")
	proto.RegisterType((*Person)(nil), "proto.Person")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersistorClient is the client API for Persistor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersistorClient interface {
	SavePersons(ctx context.Context, in *PersonsReq, opts ...grpc.CallOption) (*PersonsReply, error)
}

type persistorClient struct {
	cc *grpc.ClientConn
}

func NewPersistorClient(cc *grpc.ClientConn) PersistorClient {
	return &persistorClient{cc}
}

func (c *persistorClient) SavePersons(ctx context.Context, in *PersonsReq, opts ...grpc.CallOption) (*PersonsReply, error) {
	out := new(PersonsReply)
	err := c.cc.Invoke(ctx, "/proto.Persistor/SavePersons", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersistorServer is the server API for Persistor service.
type PersistorServer interface {
	SavePersons(context.Context, *PersonsReq) (*PersonsReply, error)
}

func RegisterPersistorServer(s *grpc.Server, srv PersistorServer) {
	s.RegisterService(&_Persistor_serviceDesc, srv)
}

func _Persistor_SavePersons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistorServer).SavePersons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Persistor/SavePersons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistorServer).SavePersons(ctx, req.(*PersonsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Persistor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Persistor",
	HandlerType: (*PersistorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SavePersons",
			Handler:    _Persistor_SavePersons_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "persistor.proto",
}

func init() { proto.RegisterFile("persistor.proto", fileDescriptor_persistor_e7bf3953f5146b35) }

var fileDescriptor_persistor_e7bf3953f5146b35 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0x87, 0xdd, 0x6d, 0xb7, 0xd2, 0xe9, 0x56, 0x71, 0xf4, 0xb0, 0x78, 0x2a, 0xf1, 0x60, 0x4f,
	0x3d, 0x54, 0xc4, 0x07, 0xd0, 0xb3, 0x94, 0x08, 0x5e, 0x25, 0x6b, 0x06, 0x09, 0xe4, 0x9f, 0x49,
	0x56, 0xe8, 0xdb, 0x4b, 0x93, 0x56, 0xad, 0xa7, 0x64, 0xbe, 0xf9, 0x66, 0x60, 0x7e, 0x70, 0xee,
	0x29, 0x44, 0x15, 0x93, 0x0b, 0x2b, 0x1f, 0x5c, 0x72, 0xd8, 0xe4, 0x87, 0xdd, 0x03, 0x6c, 0x28,
	0x44, 0x67, 0x23, 0xa7, 0x4f, 0xbc, 0x85, 0x53, 0x5f, 0xaa, 0xae, 0x5a, 0x8c, 0x96, 0xb3, 0xf5,
	0xbc, 0xd8, 0xab, 0xe2, 0xf0, 0x43, 0x97, 0xbd, 0x42, 0xfb, 0x33, 0xe6, 0xf5, 0x16, 0x19, 0xb4,
	0xef, 0x81, 0x44, 0x22, 0xf9, 0xe8, 0x06, 0x9b, 0xba, 0x6a, 0x51, 0x2d, 0x1b, 0x7e, 0xc4, 0x76,
	0xce, 0xe0, 0xe5, 0xaf, 0x53, 0x17, 0xe7, 0x2f, 0x63, 0x1f, 0x30, 0x29, 0x7b, 0xf1, 0x0c, 0x6a,
	0x25, 0xf7, 0x7b, 0x6a, 0x25, 0x11, 0x61, 0x6c, 0x85, 0xa1, 0x3c, 0x35, 0xe5, 0xf9, 0x8f, 0x57,
	0xd0, 0x90, 0x11, 0x4a, 0x77, 0xa3, 0x0c, 0x4b, 0x81, 0x37, 0x30, 0x37, 0xae, 0x57, 0x9a, 0xde,
	0xec, 0x60, 0x7a, 0x0a, 0xdd, 0x38, 0x77, 0xdb, 0x02, 0x9f, 0x33, 0x5b, 0x3f, 0xc1, 0x74, 0x73,
	0x48, 0x04, 0x1f, 0x60, 0xf6, 0x22, 0xbe, 0x68, 0x7f, 0x11, 0x5e, 0x1c, 0x1d, 0xbd, 0x0b, 0xe6,
	0xfa, 0xf2, 0x3f, 0xf2, 0x7a, 0xcb, 0x4e, 0xfa, 0x49, 0xa6, 0x77, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xc8, 0xf4, 0x91, 0x55, 0x5e, 0x01, 0x00, 0x00,
}
